name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    name: Test REST API and Build application
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'
  
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Create .env file
        run: |
          echo "BASE_URL_PRODUCTION=/vre/" >> .env
          echo "LOG_PATH=/path/to/log" >> .env
          echo "MAX_FILE_SIZE=957010000" >> .env
          echo "TIME_DIFF=3" >> .env
          echo "MINIO_PROTOCOL=http" >> .env
          echo "MINIO_URL=na" >> .env
          echo "MINIO_PORT=9000" >> .env
          echo "MINIO_USER=na" >> .env
          echo "DB_USER=na" >> .env
          echo "DB_PASS=na" >> .env
          echo "DB_SERVER=na" >> .env
          echo "DB_PORT=27017" >> .env
          echo "DB_NAME=na" >> .env
          echo "PAT=na" >> .env
          echo "NODE_NAME=dev" >> .env

      - name: Build project
        run: npm run build:production